(() => {
  let data = window.ONIGIRI_ONIGIMON_DATA || {}, selected = null, busy = false;
  const $ = s => document.querySelector(s), esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const text = (s, v) => { const n = $(s); if (n) n.textContent = v ?? ''; };
  const image = (s, url) => { const n = $(s); if (n) n.src = url || ''; };
  const status = id => (data.needs || []).find(item => item.id === id) || (data.needs || [])[0];
  const effectFor = id => ({health:'heal', happiness:'play', hygiene:'clean', training:'train', hunger:'feed'})[id] || 'sparkle';
  function toast(notice) { if (!notice.message) return; const node = $('.toast'); node.textContent = notice.message; node.className = `toast is-visible ${notice.kind || ''}`; setTimeout(() => node.className = 'toast', 3600); }
  function setModal(name, open) { const node = $(`[data-bind="${name}-modal"]`); if (node) { node.classList.toggle('is-open', open); node.setAttribute('aria-hidden', String(!open)); } }
  function setSprite(companion) { const node = $('[data-bind="sprite"]'), urls = companion.spriteUrls || []; if (!node) return; let at = 0; node.src = urls[0] || ''; node.alt = companion.name || ''; node.onerror = () => { at += 1; if (urls[at]) node.src = urls[at]; else { node.onerror = null; node.style.opacity = '.2'; } }; }
  function renderStatuses() { const box = $('[data-bind="statuses"]'); if (!box) return; box.innerHTML = (data.needs || []).map(item => `<button class="status-row ${item.id === selected ? 'is-selected' : ''}" data-status="${esc(item.id)}" style="--status:${esc(item.color)}"><span><img src="${esc(item.icon)}" alt="">${esc(item.label)}</span><b>${esc(item.detail)}</b><i><em style="width:${Math.max(0, Math.min(100, item.value))}%"></em></i></button>`).join(''); }
  function renderBackpack() { const current = status(selected), box = $('[data-bind="backpack"]'); if (!current || !box) return; text('[data-bind="selected-status"]', current.label); box.innerHTML = current.items.length ? current.items.map(item => `<button class="bag-item" data-item="${esc(item.key)}" title="${esc(item.label)}"><img src="${esc(item.icon)}" alt="${esc(item.label)}"><span>${item.count}</span></button>`).join('') : `<p class="empty-bag">${esc(current.empty || data.labels?.empty)}</p>`; }
  function renderMarket() { const box = $('[data-bind="market"]'); if (!box) return; box.innerHTML = (data.market || []).map(item => `<button class="market-card ${item.purchased ? 'is-bought' : ''}" data-buy="${esc(item.slot)}" ${item.purchased ? 'disabled' : ''}><img src="${esc(item.icon)}" alt="${esc(item.label)}"><strong>${esc(item.label)}</strong><small>x${item.amount}</small><span><img src="${esc(item.currencyIcon)}" alt="">${item.price}</span></button>`).join(''); }
  function labels() { return data.labels || {}; }
  function applyI18n(root) {
    const L = labels();
    root.querySelectorAll('[data-i18n-text]').forEach(el => { const v = L[el.dataset.i18nText]; if (v) el.textContent = v; });
    root.querySelectorAll('[data-i18n-alabel]').forEach(el => { const v = L[el.dataset.i18nAlabel]; if (v) el.setAttribute('aria-label', v); });
  }
  function render() { if (!data.companion) { $('.onigimon-app').innerHTML = `<p class="no-companion">${(data.labels || {}).noCompanion || 'No Onigimon companion selected.'}</p>`; return; } selected = status(selected)?.id || (data.needs || [])[0]?.id; const c = data.companion, a = data.assets || {}, l = data.labels || {}; applyI18n(document); text('[data-bind="name"]', c.name); text('[data-bind="level"]', `${l.level || 'Level'} ${c.level || 1}`); text('[data-bind="message"]', data.message); image('[data-bind="mart"]', a.mart); image('[data-bind="backpack"]', a.backpack); image('[data-bind="comet"]', a.comet); image('[data-bind="star-piece"]', a.starPiece); text('[data-bind="comets"]', data.wallet?.comet_shards || 0); text('[data-bind="stars"]', data.wallet?.star_pieces || 0); text('[data-bind="market-title"]', l.market); text('[data-bind="backpack-title"]', l.backpack); text('[data-bind="redeem-title"]', l.redeemTitle); text('[data-bind="redeem-hint"]', l.redeemHint); $('.redeem-submit').textContent = l.redeem; const gift = $('[data-action="gift"]'); if (gift) { gift.textContent = data.marketGiftReady ? l.dailyGift : l.giftOpened; gift.disabled = !data.marketGiftReady; } const bg = $('[data-bind="background"]'); if (bg) { bg.style.backgroundColor = a.backgroundColor || '#6ea96a'; bg.style.backgroundImage = a.background ? `url("${a.background}")` : 'none'; } setSprite(c); renderStatuses(); renderBackpack(); renderMarket(); }
  function sound(effect) { try { const Ctx = window.AudioContext || window.webkitAudioContext, ctx = new Ctx(), now = ctx.currentTime; const f = {feed:[620,820],play:[820,1080],clean:[360,660],train:[480,940],heal:[523,784]}[effect] || [800,1050]; f.forEach((hz, i) => { const o=ctx.createOscillator(), g=ctx.createGain(); o.frequency.setValueAtTime(hz, now+i*.07); g.gain.setValueAtTime(.0001, now+i*.07); g.gain.exponentialRampToValueAtTime(.075,now+i*.07+.02); g.gain.exponentialRampToValueAtTime(.0001,now+i*.07+.3); o.connect(g).connect(ctx.destination); o.start(now+i*.07); o.stop(now+i*.07+.31); }); setTimeout(()=>ctx.close(),600); } catch (_) {} }
  function animate(effect, icon) { const stage = $('.companion-stage'), layer = $('.fx-layer'), sprite = $('.companion-sprite'); if (!stage || !layer) return; sound(effect); sprite?.classList.add('is-animated'); setTimeout(()=>sprite?.classList.remove('is-animated'),700); const src = icon || (effect === 'play' ? data.assets?.star : data.assets?.heart); for(let i=0;i<12;i++){const p=document.createElement('img');p.className=`fx fx-${effect}`;p.src=src||'';p.style.setProperty('--x',`${(Math.random()-.5)*250}px`);p.style.setProperty('--y',`${-50-Math.random()*180}px`);p.style.animationDelay=`${i*35}ms`;layer.appendChild(p);p.addEventListener('animationend',()=>p.remove());} }
  function actionItem(item) { const box = $('[data-bind="action-item"]'); if (!box) return; box.classList.toggle('is-idle', !item); const img = box.querySelector('img'), label = box.querySelector('span'); if (item) { img.src=item.icon||''; label.textContent=item.label; } else { img.removeAttribute('src'); label.textContent=(data.labels || {}).idle || 'Yawn...'; } }
  function useItem(btn) { if (busy) return; const current = status(selected), item = (current?.items || []).find(i => i.key === btn.dataset.item); if (!item) return; busy=true; btn.disabled=true; actionItem(item); animate(effectFor(current.id), item.icon); setTimeout(()=>pycmd(`onigimon:use:${item.key}`),900); }
  document.addEventListener('click', event => { const s=event.target.closest('[data-status]'); if(s){selected=s.dataset.status;renderStatuses();renderBackpack();actionItem(null);return;} const item=event.target.closest('[data-item]');if(item){useItem(item);return;} const buy=event.target.closest('[data-buy]');if(buy&&!buy.disabled){busy=true;buy.disabled=true;animate('sparkle', data.assets?.star);setTimeout(()=>pycmd(`onigimon:market-buy:${buy.dataset.buy}`),450);return;} if(event.target.closest('[data-action="gift"]')){busy=true;animate('sparkle',data.assets?.star);setTimeout(()=>pycmd('onigimon:market-gift'),450);return;} if(event.target.closest('[data-action="open-redeem"]'))setModal('redeem',true); if(event.target.closest('[data-action="close-redeem"]'))setModal('redeem',false); if(event.target.closest('[data-action="close-gift"]'))setModal('gift',false); });
  document.addEventListener('submit', event => { if(!event.target.matches('[data-action="redeem-form"]'))return;event.preventDefault();const input=$('[data-bind="redeem-code"]'),code=input?.value.trim();if(code){setModal('redeem',false);pycmd(`onigimon:redeem:${code}`);} });
  document.addEventListener('keydown', event => { if(event.key==='Escape'){setModal('redeem',false);setModal('gift',false);} });
  window.onOnigimonData = (payload, notice={}) => { data=payload||{};busy=false;render();toast(notice);if(data.gift){image('[data-bind="gift-icon"]',data.gift.icon);text('[data-bind="gift-text"]',`+${data.gift.amount} ${data.gift.label}`);setModal('gift',true);} };
  document.addEventListener('DOMContentLoaded', render);
})();
