/*
    Onigiri Heatmap Renderer
    This script is responsible for drawing the heatmap graph based on review data,
    with different views for Year, Month, and Week.
*/

// Ensure the OnigiriHeatmap object exists
window.OnigiriHeatmap = window.OnigiriHeatmap || {};

(function (exports) {
    "use strict";

    // --- STATE MANAGEMENT & CACHE ---
    let state = {
        view: 'year', // 'year', 'month', 'week'
        targetDate: new Date(),
        // Earliest year with review history; bounds the year dropdown so it
        // doesn't offer years the collection has no data for.
        firstYear: new Date().getFullYear(),
    };


    // --- DATA PREPARATION ---
    function prepareData(rawData) {
        // Python now sends date keys (YYYY-MM-DD) directly.
        // These keys are already adjusted for local timezone and rollover.

        // Convert object from Python into a Map for easier lookup
        const reviewsByDay = new Map(Object.entries(rawData.calendar || {}));

        // Convert object from Python into a Map
        const duesByDay = new Map(Object.entries(rawData.due_calendar || {}));

        // Get today's date key from Python
        const todayKey = rawData.today_date_key;

        // Get daily average for relative scaling
        const dailyAverage = rawData.daily_average || 0;

        // No need to calculate offset or convert timestamps here.

        return { reviewsByDay, duesByDay, todayKey, dailyAverage };
    }

    // Classifies past review count into 8 levels (0-8) based on daily average
    function getIntensityLevel(count, dailyAverage) {
        if (count === 0) return 0;

        // Use a minimum average of 3 to avoid "1 review = max intensity" scenarios for new users
        const avg = Math.max(dailyAverage, 5);

        if (count < 0.4 * avg) return 1;
        if (count < 0.7 * avg) return 2;
        if (count < 1.0 * avg) return 3;
        if (count < 1.3 * avg) return 4;
        if (count < 1.6 * avg) return 5;
        if (count < 2.0 * avg) return 6;
        if (count < 2.5 * avg) return 7;

        // >= 2.5 * avg
        return 8;
    }

    // Classifies future due count into 8 levels (0-8) based on daily average (same scale)
    function getDueIntensityLevel(count, dailyAverage) {
        if (count === 0) return 0;

        const avg = Math.max(dailyAverage, 5);

        if (count < 0.4 * avg) return 1;
        if (count < 0.7 * avg) return 2;
        if (count < 1.0 * avg) return 3;
        if (count < 1.3 * avg) return 4;
        if (count < 1.6 * avg) return 5;
        if (count < 2.0 * avg) return 6;
        if (count < 2.5 * avg) return 7;

        return 8;
    }

    // --- HELPER FUNCTION ---

    /**
     * Formats a Date object into a YYYY-MM-DD string in its local timezone.
     * This is crucial to match the keys generated by Python.
     * @param {Date} date The input date object.
     * @returns {string} A string in "YYYY-MM-DD" format.
     */
    function getLocalDateKey(date) {
        const year = date.getFullYear();
        const month = (date.getMonth() + 1).toString().padStart(2, '0');
        const day = date.getDate().toString().padStart(2, '0');
        return `${year}-${month}-${day}`;
    }

    function escapeAttr(value) {
        return String(value)
            .replace(/&/g, '&amp;')
            .replace(/"/g, '&quot;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;');
    }

    function getWeekStartOffset(date, config) {
        const startsSunday = (config.heatmapWeekStart || 'monday') === 'sunday';
        return startsSunday ? date.getDay() : (date.getDay() + 6) % 7;
    }

    function orderedWeekdayLabels(config, longLabels) {
        const formatter = new Intl.DateTimeFormat(config.locale || undefined, {
            weekday: longLabels ? 'short' : 'narrow'
        });
        // 2024-01-07 was a Sunday. Build labels from dates rather than using
        // hard-coded English initials, then place them in the chosen order.
        const labels = Array.from({ length: 7 }, (_, day) =>
            formatter.format(new Date(2024, 0, 7 + day))
        );
        if ((config.heatmapWeekStart || 'monday') === 'sunday') {
            return labels;
        }
        return labels.slice(1).concat(labels[0]);
    }


    // --- VIEW RENDERERS ---

    function drawYearView(gridContainer, preparedData, config) {
        gridContainer.className = 'heatmap-grid year-view';
        gridContainer.dataset.monthsHidden = !config.heatmapShowMonths;
        gridContainer.dataset.weekdaysHidden = !config.heatmapShowWeekdays;

        const target = state.targetDate;
        const year = target.getFullYear();
        const firstDayOfYear = new Date(year, 0, 1);

        let html = `
            <div class="heatmap-months"></div>
            <div class="heatmap-weekdays">${orderedWeekdayLabels(config, false).map(label => `<div>${label}</div>`).join('')}</div>
            <div class="heatmap-cells"></div>
        `;
        gridContainer.innerHTML = html;

        const cellsContainer = gridContainer.querySelector('.heatmap-cells');
        const monthsContainer = gridContainer.querySelector('.heatmap-months');
        let currentMonth = -1;

        for (let i = 0; i < 371; i++) {
            const dayOfWeek = getWeekStartOffset(firstDayOfYear, config);
            const date = new Date(firstDayOfYear);
            date.setDate(firstDayOfYear.getDate() - dayOfWeek + i);

            if (date.getFullYear() !== year) {
                const emptyCell = document.createElement('div');
                emptyCell.className = 'heatmap-day-cell empty';
                cellsContainer.appendChild(emptyCell);
                continue;
            }

            if (date.getDate() === 1 && date.getMonth() !== currentMonth) {
                currentMonth = date.getMonth();
                const monthLabel = document.createElement('div');
                monthLabel.className = 'month-label';
                monthLabel.textContent = date.toLocaleString(config.locale || undefined, { month: 'short' });
                // Span the month's own weeks, so a label can't drift over the
                // next month's columns when the widget is narrow.
                monthLabel.style.gridColumn = `${Math.floor(i / 7) + 1} / span 4`;
                monthsContainer.appendChild(monthLabel);
            }

            const dateKey = getLocalDateKey(date); // FIX: Use local date key
            const reviewCount = preparedData.reviewsByDay.get(dateKey) || 0;
            const dueCount = preparedData.duesByDay.get(dateKey) || 0;
            const cell = createCell(date, reviewCount, dueCount, config, preparedData.todayKey, preparedData.dailyAverage);
            cellsContainer.appendChild(cell);
        }
    }

    function drawMonthView(gridContainer, preparedData, config) {
        gridContainer.className = 'heatmap-grid month-view';
        gridContainer.dataset.weekdaysHidden = !config.heatmapShowWeekdays;
        const target = state.targetDate;
        const year = target.getFullYear();
        const month = target.getMonth();
        const firstDayOfMonth = new Date(year, month, 1);

        let html = `
            <div class="month-weekdays-header">${orderedWeekdayLabels(config, true).map(label => `<div>${label}</div>`).join('')}</div>
            <div class="month-cells-grid"></div>
        `;
        gridContainer.innerHTML = html;
        const cellsContainer = gridContainer.querySelector('.month-cells-grid');

        const firstDayOfWeek = getWeekStartOffset(firstDayOfMonth, config);
        for (let i = 0; i < firstDayOfWeek; i++) {
            const emptyCell = document.createElement('div');
            emptyCell.className = 'heatmap-day-cell empty';
            cellsContainer.appendChild(emptyCell);
        }

        const lastDayOfMonth = new Date(year, month + 1, 0).getDate();
        for (let i = 1; i <= lastDayOfMonth; i++) {
            const date = new Date(year, month, i);
            const dateKey = getLocalDateKey(date); // FIX: Use local date key
            const reviewCount = preparedData.reviewsByDay.get(dateKey) || 0;
            const dueCount = preparedData.duesByDay.get(dateKey) || 0;
            const cell = createCell(date, reviewCount, dueCount, config, preparedData.todayKey, preparedData.dailyAverage);
            cellsContainer.appendChild(cell);
        }
    }

    function drawWeekView(gridContainer, preparedData, config) {
        gridContainer.className = 'heatmap-grid week-view';
        gridContainer.dataset.headerHidden = !config.heatmapShowWeekHeader;
        const target = state.targetDate;
        const startDate = new Date(target);
        const startDayOfWeek = getWeekStartOffset(target, config);
        startDate.setDate(startDate.getDate() - startDayOfWeek);

        let html = `
            <div class="week-days-header"></div>
            <div class="week-cells-grid"></div>
        `;
        gridContainer.innerHTML = html;

        const headerContainer = gridContainer.querySelector('.week-days-header');
        const cellsContainer = gridContainer.querySelector('.week-cells-grid');

        for (let i = 0; i < 7; i++) {
            const date = new Date(startDate);
            date.setDate(startDate.getDate() + i);

            const header = document.createElement('div');
            header.innerHTML = `
                <div class="weekday-label">${date.toLocaleString(config.locale || undefined, { weekday: 'short' })}</div>
                <div class="day-label">${date.getDate()}</div>
            `;
            headerContainer.appendChild(header);

            const dateKey = getLocalDateKey(date); // FIX: Use local date key
            const reviewCount = preparedData.reviewsByDay.get(dateKey) || 0;
            const dueCount = preparedData.duesByDay.get(dateKey) || 0;
            const cell = createCell(date, reviewCount, dueCount, config, preparedData.todayKey, preparedData.dailyAverage);
            cellsContainer.appendChild(cell);
        }
    }

    function createCell(date, reviewCount, dueCount, config, todayKey, dailyAverage) {
        const cell = document.createElement('div');
        cell.className = 'heatmap-day-cell';

        const dateKey = getLocalDateKey(date); // FIX: Use local date key
        let tooltipText;
        const dateText = date.toLocaleDateString(config.locale || undefined, { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });

        if (dateKey === todayKey) {
            // --- TODAY ---
            // Mark today's cell with a special class
            cell.classList.add('today');

            // Set review count and level for proper coloring
            cell.dataset.reviewCount = reviewCount;
            cell.dataset.level = getIntensityLevel(reviewCount, dailyAverage);

            // Build tooltip with reviews done today
            tooltipText = `${reviewCount} review${reviewCount !== 1 ? 's' : ''} done today`;
        } else if (dateKey < todayKey) {
            // --- PAST ---
            cell.dataset.reviewCount = reviewCount;
            cell.dataset.level = getIntensityLevel(reviewCount, dailyAverage);
            tooltipText = `${reviewCount} review${reviewCount !== 1 ? 's' : ''} on ${dateText}`;
        } else {
            // --- FUTURE ---
            cell.classList.add('future-day');
            cell.dataset.dueCount = dueCount;
            cell.dataset.dueLevel = getDueIntensityLevel(dueCount, dailyAverage);

            const dueText = `${dueCount} review${dueCount !== 1 ? 's' : ''} due`;
            tooltipText = `${dueText} on ${dateText}`;
        }

        const shapeDiv = document.createElement('div');
        shapeDiv.className = 'day-shape';
        // The mask image itself lives in the --heatmap-shape-mask custom
        // property on the container (see setShapeMaskVariable). Setting the
        // data: URI inline on every cell made Chromium track one image
        // resource per day cell, so each deck browser render piled up hundreds
        // more of them and the whole webview got slower the longer Anki ran.
        cell.appendChild(shapeDiv);

        cell.setAttribute('data-tooltip', tooltipText);

        // Match Review Heatmap's behavior: only days backed by cards are
        // actionable. Past/today cells open review history; future cells open
        // the due forecast. The Python bridge decides which exact Anki search
        // to use from this canonical date key.
        const browsableCount = dateKey > todayKey ? dueCount : reviewCount;
        if (browsableCount > 0) {
            const browseLabel = (config.i18n && config.i18n.browse) || 'Browse';
            cell.classList.add('browsable');
            cell.dataset.dateKey = dateKey;
            cell.setAttribute('role', 'button');
            cell.setAttribute('tabindex', '0');
            cell.setAttribute('aria-label', `${tooltipText}. ${browseLabel}`);
        }
        return cell;
    }

    function openCellInBrowser(cell) {
        if (!cell || !cell.dataset.dateKey || typeof pycmd !== 'function') return;
        pycmd(`onigiri_heatmap_browse:${cell.dataset.dateKey}`);
    }

    function bindCellInteractions(gridContainer) {
        gridContainer.addEventListener('click', (event) => {
            openCellInBrowser(event.target.closest('.heatmap-day-cell.browsable'));
        });
        gridContainer.addEventListener('keydown', (event) => {
            if (event.key !== 'Enter' && event.key !== ' ') return;
            const cell = event.target.closest('.heatmap-day-cell.browsable');
            if (!cell) return;
            event.preventDefault();
            openCellInBrowser(cell);
        });
    }

    // `animate: false` places the pill without the slide. Every redraw rebuilds
    // the header, so the fresh pill starts at width 0 — animating that would
    // flash the active view as unselected for a frame.
    function updateFilterPill(container, animate) {
        const filters = container.querySelector('.heatmap-filters');
        const pill = filters ? filters.querySelector('.heatmap-filter-pill') : null;
        const active = filters ? filters.querySelector('.filter-btn.active') : null;
        if (!filters || !pill || !active) return;
        const filterRect = filters.getBoundingClientRect();
        const activeRect = active.getBoundingClientRect();
        // `left: 0` resolves against the track's padding box, whose edge is the
        // inside of the border — the padding is not an origin offset, so the
        // button's distance from the border box is the whole translation.
        if (animate === false) {
            pill.style.transition = 'none';
        }
        pill.style.width = `${activeRect.width}px`;
        pill.style.transform = `translateX(${activeRect.left - filterRect.left}px)`;
        if (animate === false) {
            // Flush the transition-less placement before restoring the
            // transition, otherwise the browser coalesces both and animates.
            void pill.offsetWidth;
            pill.style.transition = '';
        }
    }

    // Keeps the calendar inside the widget box instead of letting it spill past
    // the bottom edge (the container clips). Shrink-only: a container whose
    // height is driven by its own content — the profile sidebar — never reports
    // an overflow, so it keeps the base sizes.
    function fitGridToContainer(container, gridContainer) {
        gridContainer.style.removeProperty('--hm-cell');
        gridContainer.style.removeProperty('max-width');

        const containerStyle = window.getComputedStyle(container);
        const header = container.querySelector('.onigiri-heatmap-header');
        let room = container.clientHeight
            - parseFloat(containerStyle.paddingTop || 0)
            - parseFloat(containerStyle.paddingBottom || 0);
        if (header) {
            room -= header.offsetHeight
                + parseFloat(window.getComputedStyle(header).marginBottom || 0);
        }
        if (!(room > 0)) return;

        const isYear = gridContainer.classList.contains('year-view');
        // The month/week labels and the year view's month row don't scale with
        // the cells, so one division under-shoots; a few passes converge.
        for (let pass = 0; pass < 4; pass++) {
            const need = gridContainer.offsetHeight;
            if (need <= room + 0.5) return;
            const factor = room / need;
            if (isYear) {
                // Year cells are 1fr columns, so their height follows the
                // grid's width — narrowing the grid is what shortens it.
                const width = gridContainer.getBoundingClientRect().width;
                const nextWidth = Math.max(120, Math.floor(width * factor));
                if (nextWidth >= width) return;
                gridContainer.style.maxWidth = nextWidth + 'px';
            } else {
                const cell = parseFloat(
                    window.getComputedStyle(gridContainer).getPropertyValue('--hm-cell')
                ) || 30;
                const nextCell = Math.max(12, Math.floor(cell * factor));
                if (nextCell >= cell) return;
                gridContainer.style.setProperty('--hm-cell', nextCell + 'px');
            }
        }
    }

    // --- MAIN RENDER FUNCTION ---
    function setShapeMaskVariable(container, config) {
        // One mask resource for the whole grid instead of one per day cell.
        if (!config.heatmapSvgContent) {
            container.style.removeProperty('--heatmap-shape-mask');
            return;
        }
        const encodedSvg = encodeURIComponent(config.heatmapSvgContent);
        container.style.setProperty(
            '--heatmap-shape-mask',
            `url("data:image/svg+xml,${encodedSvg}")`
        );
    }

    // Year picker shown in place of the static year title, listing every year
    // from the current one back to the collection's first year with reviews.
    function buildYearSelect() {
        const currentYear = state.targetDate.getFullYear();
        const thisYear = new Date().getFullYear();
        const firstYear = Math.min(state.firstYear || thisYear, thisYear);
        let items = '';
        for (let y = thisYear; y >= firstYear; y--) {
            items += `<div class="year-dropdown-item${y === currentYear ? ' selected' : ''}" data-year="${y}">${y}</div>`;
        }
        return `
            <div class="year-select-wrapper">
                <button class="nav-btn year-select-btn" type="button"><span class="year-select-label">${currentYear}</span></button>
                <div class="year-dropdown-menu">${items}</div>
            </div>
        `;
    }

    exports.render = function (containerId, data, config) {
        const container = document.getElementById(containerId);
        if (!container) return;

        setShapeMaskVariable(container, config);

        const preparedData = prepareData(data);

        if (typeof data.firstYear === 'number') {
            state.firstYear = data.firstYear;
        }

        // Initialize view from config if available (defaulting to 'year' is handled by config.py/heatmap.py logic, but fallback here too)
        if (config.heatmapDefaultView) {
            state.view = config.heatmapDefaultView;
        }

        function draw() {
            const i18n = config.i18n || {};
            const hasStreak = data.streak > 0;
            const streakIconColor = hasStreak
                ? (config.heatmapStreakIconColor || '#ff6b35')
                : (config.heatmapStreakIconZeroColor || '#8f8f8f');
            const defaultStreakSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22a7.5 7.5 0 0 0 7.5-7.5c0-1 0-3-2-5.5c0 0-.1 2.854-2.074 2.44c-3.193-.667.93-6.937-4.926-9.44c0 5-6 6.5-6 12.5A7.5 7.5 0 0 0 12 22Z"/></svg>`;
            const configuredStreakSvg = (config.heatmapStreakIconSvgContent || defaultStreakSvg)
                .replace(/<path\b([^>]*?)fill=["']none["'][^>]*>\s*<\/path>/gi, '')
                .replace(/<path\b([^>]*?)fill=["']none["'][^>]*\/>/gi, '');
            const fireSvg = configuredStreakSvg.replace(
                /<svg\b/i,
                `<svg class="streak-icon${hasStreak ? ' active' : ''}" style="color:${escapeAttr(streakIconColor)};fill:currentColor;"`
            );
            const longestStreak = data.longest_streak || 0;
            const streakTip = longestStreak > 0
                ? `Longest streak: ${longestStreak} day${longestStreak !== 1 ? 's' : ''}`
                : 'No streak yet';
            const streakLabel = i18n.day_streak || 'day streak';
            const streakHTML = config.heatmapShowStreak
                ? `<div class="streak-counter onigiri-streak-tip" data-tooltip="${escapeAttr(streakTip)}">${fireSvg}<span class="streak-count">${data.streak}</span><span class="streak-label">${streakLabel}</span></div>`
                : '';

            let navHTML = '';
            if (state.view === 'year') {
                navHTML = `
                    <button class="nav-btn" data-nav="-1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M201.4 297.4C188.9 309.9 188.9 330.2 201.4 342.7L361.4 502.7C373.9 515.2 394.2 515.2 406.7 502.7C419.2 490.2 419.2 469.9 406.7 457.4L269.3 320L406.6 182.6C419.1 170.1 419.1 149.8 406.6 137.3C394.1 124.8 373.8 124.8 361.3 137.3L201.3 297.3z"/></svg></button>
                    ${buildYearSelect()}
                    <button class="nav-btn" data-nav="1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M439.1 297.4C451.6 309.9 451.6 330.2 439.1 342.7L279.1 502.7C266.6 515.2 246.3 515.2 233.8 502.7C221.3 490.2 221.3 469.9 233.8 457.4L371.2 320L233.9 182.6C221.4 170.1 221.4 149.8 233.9 137.3C246.4 124.8 266.7 124.8 279.2 137.3L439.2 297.3z"/></svg></button>
                `;
            } else if (state.view === 'month') {
                navHTML = `
                    <button class="nav-btn" data-nav="-1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M201.4 297.4C188.9 309.9 188.9 330.2 201.4 342.7L361.4 502.7C373.9 515.2 394.2 515.2 406.7 502.7C419.2 490.2 419.2 469.9 406.7 457.4L269.3 320L406.6 182.6C419.1 170.1 419.1 149.8 406.6 137.3C394.1 124.8 373.8 124.8 361.3 137.3L201.3 297.3z"/></svg></button>
                    <span class="nav-title">${state.targetDate.toLocaleString(config.locale || undefined, { month: 'short', year: 'numeric' })}</span>
                    <button class="nav-btn" data-nav="1"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M439.1 297.4C451.6 309.9 451.6 330.2 439.1 342.7L279.1 502.7C266.6 515.2 246.3 515.2 233.8 502.7C221.3 490.2 221.3 469.9 233.8 457.4L371.2 320L233.9 182.6C221.4 170.1 221.4 149.8 233.9 137.3C246.4 124.8 266.7 124.8 279.2 137.3L439.2 297.3z"/></svg></button>
                `;
            } else if (state.view === 'week') {
                const startOfWeek = new Date(state.targetDate);
                startOfWeek.setDate(startOfWeek.getDate() - (startOfWeek.getDay() + 6) % 7);
                const endOfWeek = new Date(startOfWeek);
                endOfWeek.setDate(startOfWeek.getDate() + 6);
                navHTML = `
                    <button class="nav-btn" data-nav="-7"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M201.4 297.4C188.9 309.9 188.9 330.2 201.4 342.7L361.4 502.7C373.9 515.2 394.2 515.2 406.7 502.7C419.2 490.2 419.2 469.9 406.7 457.4L269.3 320L406.6 182.6C419.1 170.1 419.1 149.8 406.6 137.3C394.1 124.8 373.8 124.8 361.3 137.3L201.3 297.3z"/></svg></button>
                    <span class="nav-title">${startOfWeek.toLocaleDateString(config.locale || undefined, { month: 'short', day: 'numeric' })} - ${endOfWeek.toLocaleDateString(config.locale || undefined, { month: 'short', day: 'numeric' })}</span>
                    <button class="nav-btn" data-nav="7"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path d="M439.1 297.4C451.6 309.9 451.6 330.2 439.1 342.7L279.1 502.7C266.6 515.2 246.3 515.2 233.8 502.7C221.3 490.2 221.3 469.9 233.8 457.4L371.2 320L233.9 182.6C221.4 170.1 221.4 149.8 233.9 137.3C246.4 124.8 266.7 124.8 279.2 137.3L439.2 297.3z"/></svg></button>
                `;
            }

            const previousPill = container.querySelector('.heatmap-filter-pill');
            const carriedPill = previousPill
                ? { width: previousPill.style.width, transform: previousPill.style.transform }
                : null;

            // Title alone on the left; the three pills — streak, date stepper,
            // view switcher — are one group on the right, read left to right.
            container.innerHTML = `
                <div class="onigiri-heatmap-header">
                    <div class="header-left">
                        <h3 class="heatmap-title">${(i18n.activity || 'Activity').toUpperCase()}</h3>
                    </div>
                    <div class="header-right">
                        ${streakHTML}
                        <div class="heatmap-nav">${navHTML}</div>
                        <div class="heatmap-filters">
                            <span class="heatmap-filter-pill"></span>
                            <button class="filter-btn ${state.view === 'year' ? 'active' : ''}" data-view="year">${i18n.year || 'Year'}</button>
                            <button class="filter-btn ${state.view === 'month' ? 'active' : ''}" data-view="month">${i18n.month || 'Month'}</button>
                            <button class="filter-btn ${state.view === 'week' ? 'active' : ''}" data-view="week">${i18n.week || 'Week'}</button>
                        </div>
                    </div>
                </div>
                <div class="heatmap-grid"></div>
            `;

            const gridContainer = container.querySelector('.heatmap-grid');
            if (state.view === 'year') {
                drawYearView(gridContainer, preparedData, config);
            } else if (state.view === 'month') {
                drawMonthView(gridContainer, preparedData, config);
            } else if (state.view === 'week') {
                drawWeekView(gridContainer, preparedData, config);
            }
            bindCellInteractions(gridContainer);
            // Placed synchronously, before this frame paints — a deferred
            // placement leaves one frame with no pill under the active view.
            // When a pill was already on screen its geometry is carried across
            // the rebuild, so switching views slides from the old position
            // instead of growing out of nothing.
            const pill = container.querySelector('.heatmap-filter-pill');
            updateFilterPill(container, false);

            // Animated *away from* the previous position rather than towards
            // the new one: the pill already holds its final geometry, so a
            // frame that never arrives leaves it correct instead of parked
            // under the wrong view. Stepping the date carries the geometry it
            // ends on, so only a real view switch moves anything.
            if (pill && carriedPill && carriedPill.width
                && typeof pill.animate === 'function'
                && (carriedPill.width !== pill.style.width
                    || carriedPill.transform !== pill.style.transform)) {
                pill.animate(
                    [
                        { width: carriedPill.width, transform: carriedPill.transform },
                        { width: pill.style.width, transform: pill.style.transform }
                    ],
                    { duration: 180, easing: 'cubic-bezier(0.16, 1, 0.3, 1)' }
                );
            }

            gridContainer.classList.add('is-entering');
            window.setTimeout(() => gridContainer.classList.remove('is-entering'), 180);

            // Re-measures the pill and the calendar against the box they
            // actually got. Both depend on text metrics, so the first frame
            // can still be measuring a fallback font.
            const reflow = () => {
                updateFilterPill(container);
                const grid = container.querySelector('.heatmap-grid');
                if (grid) fitGridToContainer(container, grid);
            };
            requestAnimationFrame(reflow);

            container.querySelector('.heatmap-filters').addEventListener('click', (e) => {
                if (e.target.classList.contains('filter-btn')) {
                    state.view = e.target.dataset.view;
                    state.targetDate = new Date();
                    draw();
                }
            });

            container.querySelector('.heatmap-nav').addEventListener('click', (e) => {
                // Only the prev/next arrows carry data-nav. The year button also
                // has .nav-btn (for shared styling) but must not navigate — it
                // opens the dropdown, handled below.
                const navBtn = e.target.closest('.nav-btn[data-nav]');
                if (navBtn) {
                    const navAmount = parseInt(navBtn.dataset.nav, 10);
                    if (state.view === 'year') {
                        state.targetDate.setFullYear(state.targetDate.getFullYear() + navAmount);
                    } else if (state.view === 'month') {
                        state.targetDate.setMonth(state.targetDate.getMonth() + navAmount);
                    } else if (state.view === 'week') {
                        state.targetDate.setDate(state.targetDate.getDate() + navAmount);
                    }
                    draw();
                    return;
                }

                const menu = container.querySelector('.year-dropdown-menu');
                const selectBtn = container.querySelector('.year-select-btn');
                const closeDropdown = () => {
                    if (menu) menu.classList.remove('open');
                    if (selectBtn) selectBtn.classList.remove('open');
                };

                const item = e.target.closest('.year-dropdown-item');
                if (item) {
                    const year = parseInt(item.dataset.year, 10);
                    if (!isNaN(year) && year !== state.targetDate.getFullYear()) {
                        state.targetDate.setFullYear(year);
                        draw();
                    } else {
                        closeDropdown();
                    }
                    return;
                }

                if (e.target.closest('.year-select-btn')) {
                    if (menu) menu.classList.toggle('open');
                    if (selectBtn) selectBtn.classList.toggle('open');
                    return;
                }

                closeDropdown();
            });
            if (!container.dataset.heatmapPillResizeBound) {
                container.dataset.heatmapPillResizeBound = 'true';
                window.addEventListener('resize', reflow, { passive: true });
                // The deck browser lays the widget grid out after this script
                // runs, so the first measurement can be of a box that isn't
                // the final one. Both hooks below are no-ops once the sizes
                // already fit — fitGridToContainer only ever shrinks.
                if (window.ResizeObserver) {
                    new ResizeObserver(reflow).observe(container);
                }
                if (document.fonts && document.fonts.ready) {
                    document.fonts.ready.then(reflow).catch(() => { });
                }
                // The nav-scoped handler above can't see clicks that land
                // elsewhere on the page, so close the year dropdown from here.
                document.addEventListener('click', (e) => {
                    if (e.target.closest && e.target.closest('.year-select-wrapper')) return;
                    const menu = container.querySelector('.year-dropdown-menu.open');
                    if (menu) menu.classList.remove('open');
                    const btn = container.querySelector('.year-select-btn.open');
                    if (btn) btn.classList.remove('open');
                });
            }
        }

        draw();
    };

    // --- AUTO-RENDERER ---
    exports.autoRender = function() {
        if (window.onigiriHeatmapData && window.onigiriHeatmapConfig) {
            exports.render('onigiri-heatmap-container', window.onigiriHeatmapData, window.onigiriHeatmapConfig);
            if (typeof window.onigiriDismissOverlay === 'function') {
                window.onigiriDismissOverlay('heatmap');
            }
            return true;
        }
        return false;
    };

    // Self-initialize if data is already present in the DOM
    (function () {
        const tryAutoRender = () => {
            if (exports.autoRender()) {
                return;
            }
            // If data not yet available, poll for a short while
            let attempts = 0;
            const interval = setInterval(() => {
                attempts++;
                if (exports.autoRender() || attempts > 20) {
                    clearInterval(interval);
                }
            }, 100);
        };

        if (document.readyState === 'loading') {
            document.addEventListener('DOMContentLoaded', tryAutoRender);
        } else {
            tryAutoRender();
        }
    })();

})(window.OnigiriHeatmap);
